//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRVInvoiceElectronic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceFileHeader
    {
        public string Prefix { get; set; }
        public decimal DocumentNumber1 { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string AcquirerPersonTypeId { get; set; }
        public string AcquirerRegimenTypeId { get; set; }
        public string AcquirerFirstName { get; set; }
        public Nullable<int> AcquirerMiddleName { get; set; }
        public Nullable<int> AcquirerLastName { get; set; }
        public string AcquirerDocumentTypeId { get; set; }
        public string AcquirerDocumentNumber { get; set; }
        public Nullable<int> AcquirerDocumentNumberCheck { get; set; }
        public string AcquirerTelephoneNumber { get; set; }
        public string AcquirerAddress { get; set; }
        public string AcquirerCity { get; set; }
        public string AcquirerDepartment { get; set; }
        public string AcquirerEmail { get; set; }
        public string Currency { get; set; }
        public int TRM { get; set; }
        public Nullable<decimal> SubTotalAmount { get; set; }
        public Nullable<decimal> TaxTotalAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Observation1 { get; set; }
        public int TaxCode { get; set; }
        public string TaxPercent { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public string ItemDescription1 { get; set; }
        public int Amount { get; set; }
    }
}
